apiVersion: autoscalling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-nginx
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-nginx
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resouce:
        name: cpu
        targetAverageUtilization: 50
    - type: Pods
      pods:
        metricName: packets-per-second
        targetAverageValue: 1k
    - type: Object
      object:
        metricName: requests-per-second
        target:
          apiVersion: extensions/v1
          kind: Ingress
          name: main-route
        targetValue: 10k
status:
  observedGeneration: 1
  
