apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  restartPolicy: Never
  containers:
    - name: write
      image: ubuntu:14.04
      command: ["bash", "-c", "echo \"hello world!\" > /data/hello"]
      volumeMounts:
        - name: data
          mountPath: /data
    - name: hello
      image: ubuntu:14.04
      command: ["bash", "-c", "sleep 10; cat /data/hello"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      hostPath:
        path: /tmp