apiVersion: v1
kind: POD
metadata:
  name: my-nginx
spec:
# hostnetwork 容器的所有端口都直接映射到主机上
  hostNetwork: true
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80