apiVersion: v1
kind: Pod
metadata:
  name: javaweb
spec:
  restartPolicy: Never
  containers:
    - name: war
      image: resouer/sample:v2
      lifecycle:
        postStart:
          exec:
            command:
              - cp
              - /sample.war
              - /app
        preStop:
          httpGet:
            host: monitor.com
            path: /warning
            port: 8080
            scheme: HTTP