apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
spec:
  hostNetwork: true
  containers:
    - name: app
      image: ubuntu:14.04
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
          hostIP: 0.0.0.0
          hostPort: 80