apiVersion: v1
kind: Pod
metadata:
  name: extended-resources-demo-2
  namespace: example
spec:
  containers:
    - name: extended-resources-demo-2-ctr
      image: nginx
      resources:
        requests:
          example.com/dongle: 2
        limits:
          example.com/dongle: 2