apiVersion: batch/v1
kind: Job
metadata:
  name: job-banana
  labels:
    jobgroup: jobexample
spec:
  template:
    metadata:
      labels:
        jobgroup: jobexample
    spec:
      containers:
        - name: busybox
          image: busybox
          command:
            - sh
            - -c
            - echo processing item banana && sleep 5
      restartPolicy: Never
