apiVersion: v1
kind: Service
metadata:
  name: my-nginx
spec:
  selector:
    name: nginx
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 32222
      protocol: TCP
# 会话保持路由选择
  sessionAffinity: ClientIP