apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    name: nginx
  ports:
    - port: 80
      targetport: 8080
      protocol: TCP
# headless service，无service ip
  clusterIP: none