apiVersion: v1
kind: ReplicationController
metadata:
  name: my-web
spec:
  replicas: 2
  selector:
    app: my-web
  template:
    metadata:
      labels:
        app: my-web
        version: v1
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80