apiVersion: v1
kind: ReplicationController
metadata:
  name: my-web-v2
spec:
  selector:
    app: my-web
    version: v2
  template:
    metadata:
      labels:
        app: my-web
        version: v2
    spec:
      containers:
        - name: my-web
          image: ubuntu:16.04
          command:
            - /bin/bash
            - -c
            - while true;do echo hello;sleep 60;done;
          ports:
            - containerPort: 80
              protocol: TCP
