apiVersion: v1
kind: Pod
metadata:
  name: qos-demo
  namespace: example
spec:
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  containers:
    - name: qos-demo-ctr
      image: nginx
      resources:
        requests:
          memory: "200Mi"
          cpu: "100m"
        limits:
          memory: "200Mi"
          cpu: "100m"