apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-slave
spec:
  replicas: 2
  selector:
    name: redis-slave
  template:
    metadata:
      labels:
        name: redis-slave
    spec:
      containers:
        - name: redis-slave
          image: kubeguide/guestbook-redis-slave
          ports:
            - containerPort: 6379
          # env:
          #   - name: GET_HOSTS_FROM
          #     value: env