apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
          env:
            - name: NGINX_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: username
            - name: NGINX_PASSWD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: password
