apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
          name: http
          hostPort: 5332
      volumeMounts:
        - name: my-mount
          mountPath: /etc/secrets
          readOnly: true
  volumes:
    - name: my-mount
      secret:
        secretName: my-secret
        items:
          - key: password
            mode: 511
            path: tst/psd
          - key: username
            mode: 511
            path: tst/usr