apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-pod
      image: busybox
      command:
        - /bin/sh
        - -c
        - while true;do echo hello;sleep 600;done
      ports:
        - containerPort: 80
          protocol: TCP
          name: http
      volumeMounts:
        - name: secrets
          mountPath: /etc/secret
          readOnly: true
  volumes:
    - name: secrets
      secret:
        secretName: my-secret