apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  namespace: example
spec:
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  containers:
    - name: cpu-demo-ctr
      image: vish/stress
      resources:
        requests:
          cpu: "100"
        limits:
          cpu: "100"
      args:
        - -cpus
        - "2"