apiVersion: v1
kind: Pod
metadata:
  name: memory-demo-2
  namespace: example
spec:
  containers:
    - name: memory-demo-ctr-2
      image: polinus/stress
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: 50Mi
        limits:
          memory: 100Mi
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
  terminationGracePeriodSeconds: 30
  restartPolicy: Always