apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo-4
  namespace: example
spec:
  containers:
    - name: sec-ctx-ctr
      image: gcr.io/google-samples/node-hello:1.0
      securityContext:
        capabilities:
          add: ["NET_ADMIN", "SYS_TIME"]