apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: example
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      name: mysql-port
  clusterIP: None

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: example
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: example
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
          volumeMounts:
            - name: mysql-pv-vol
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-pv-vol
          persistentVolumeClaim:
            claimName: mysql-pv-claim