apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  namespace: example
  annotations:
    pv.beta.kubernetes.io/gid: "1234"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /Users/yihong/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pv-claim
  namespace: example
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: pv-test
  namespace: example
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: pv-claim
          mountPath: /usr/share/nginx/html
  volumes:
    - name: pv-claim
      persistentVolumeClaim:
        claimName: my-pv-claim