apiVersion: v1
kind: Pod
metadata:
  name: vol-pod
spec:
  containers:
    - name: test-container
      image: busybox
      command: ["/bin/sh", "-c", "cat /etc/config/special.how"]
      volumeMounts:
        - name: my-mount
          mountPath: /etc/config
  volumes:
    - name: my-mount
      configMap:
        name: my-config
  restartPolicy: Never
