apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: busybox
      command: ["/bin/sh", "-c", "echo ${SPECIAL_LEVEL_KEY}, ${SPECIAL_TYPE_KEY}"]
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: special.how
        - name: SPECIAL_TYPE_KEY
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: special.type
      envFrom:
        - configMapRef:
            name: env-config
  restartPolicy: Never