apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      # env:
      #   - name: APP_LOG_LEVEL
      #     valueFrom:
      #       configMapKeyRef:
      #         name: my-config
      #         key: apploglevel
      #   - name: APP_DATA_DIR
      #     valueFrom:
      #       configMapKeyRef:
      #         name: my-config
      #         key: appdatadir
      envFrom:
        - configMapRef:
            name: my-config
